name = "LeanSketcher"
version = "0.1.0"
defaultTargets = ["leansketcher"]

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "LeanSketcher"

[[lean_exe]]
name = "leansketcher"
root = "Main"


